### ISSUE TITLE
Handle 500 error when headers are already sent

### ISSUE THREAD

**Issue by niklaswolf** [niklaswolf/nuxt3-cache-keys#1]
Error message:
```
[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:400:5)  
  at ServerResponse.setHeader (node:_http_outgoing:663:11)  
  at ./node_modules/nuxt-cache-keys/dist/runtime/plugin.mjs:20:42  
  at ./node_modules/hookable/dist/index.mjs:48:66  
  at Object.run (./node_modules/hookable/dist/index.mjs:41:43)  
  at ./node_modules/hookable/dist/index.mjs:48:56  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./.nuxt/dev/index.mjs:860:3  
  at async ./.nuxt/dev/index.mjs:378:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1212:19)
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                                                                                                               10:20:24
```

**Comment by niklaswolf** [comment]
fixed in version 1.0.2
